#server:
#  port: 8081
#
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: groupOne
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: groupOne
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # Allows deserialization of all packages
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        kafka:
          producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          consumer:
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            add:
              type:
                headers: false  # Ensures clean JSON serialization without extra type metadata
